[package]
name = "notification_daemon"
version = "0.1.0"
authors = ["rhys <rhysormond@gmail.com>"]
edition = "2018"

[dependencies]
github_notifications = { version = "0.1.0", path = "../" }
env_logger = "0.7.1"
log = "0.4.8"
chrono = "0.4.10"
futures = "0.3.1"
